FROM ruby:3.3.8

# 基本パッケージインストール
RUN apt-get update -qq && \
    apt-get install -y \
      nodejs \
      npm \
      postgresql-client \
      curl \
      gnupg && \
    curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg && \
    chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null && \
    apt-get update && \
    apt-get install -y gh && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Gemfile関連
COPY Gemfile Gemfile.lock ./
RUN bundle install

# アプリケーションファイル
COPY . .

EXPOSE 3000
CMD ["rails", "server", "-b", "0.0.0.0"]